extend type Card {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Card", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Card` table.
  """
  _count: Int! @fdc_generated(from: "Card.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Card` table where the `cardname` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cardname_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Card.cardname", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Card` table where the `hp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Card.hp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Card` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Card.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Card` table where the `typing` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  typing_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Card.typing", purpose: QUERY_COUNT)
  """
  ✨ Sum the `hp` field in the `Card` table.
  """
  hp_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Card.hp", purpose: QUERY_SUM)
  """
  ✨ Average the `hp` field in the `Card` table.
  """
  hp_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Card.hp", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `hp` field in the `Card` table.
  """
  hp_min: Int @fdc_generated(from: "Card.hp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `hp` field in the `Card` table.
  """
  hp_max: Int @fdc_generated(from: "Card.hp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Card.id", purpose: GLOBAL_ID)
}
extend type Mug {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Mug", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Mug` table.
  """
  _count: Int! @fdc_generated(from: "Mug.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mug` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mug.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mug` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mug.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mug` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mug.title", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Mug` table where the `url` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  url_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Mug.url", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Mug.id", purpose: GLOBAL_ID)
}
